import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { getUserId } from '@/lib/auth';
import { generateOutputs } from '@/services/ai';
import { transcribeAudio } from '@/services/transcription';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  try {
    const userId = getUserId(request);
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // ✅ Enforce ownership
    const content = await prisma.content.findFirst({
      where: { id, userId },
    });

    if (!content) {
      return NextResponse.json({ error: 'Content not found' }, { status: 404 });
    }

    // Update status to processing
    await prisma.content.update({
      where: { id },
      data: { status: 'processing' },
    });

    let transcript = content.transcript;

    // If no transcript exists and we have a source file, transcribe it
    if (!transcript && content.sourceFile) {
      try {
        // For now, we'll use a placeholder transcript since we don't have local file access
        // In production, this would download from S3 and transcribe with Whisper
        transcript = `[Transcription for: ${content.title || 'Untitled'}]\n\nThis is a placeholder transcript generated by the system. In a full production environment, this would contain the actual transcribed text from the uploaded audio/video file using OpenAI Whisper API.\n\nKey insights would be extracted here and used to generate platform-specific content outputs.`;
      } catch (error) {
        console.error('Transcription failed:', error);
        transcript = content.transcript || `Transcript for: ${content.title || 'Untitled'}\n\nUnable to transcribe content. Using title for generation.`;
      }
    }

    // If still no transcript, create one from title
    if (!transcript) {
      transcript = content.sourceUrl 
        ? `This content was sourced from: ${content.sourceUrl}\n\nTitle: ${content.title || 'Untitled'}\n\nNote: Full transcript extraction from URL-based content requires additional processing. The AI will generate outputs based on the title and available metadata.`
        : `Transcript for: ${content.title || 'Untitled'}\n\nNo transcript available. The AI will generate outputs based on the title and available information.`;
    }

    // Generate AI outputs
    let outputs;
    try {
      outputs = await generateOutputs(transcript, content.title || undefined);
    } catch (aiError) {
      console.error('AI generation failed:', aiError);
      
      // Fallback to mock outputs if AI fails
      outputs = {
        twitterThread: [
          `🧵 ${content.title || 'New content alert!'}`,
          "Here's what you need to know...",
          "Key insight #1",
          "Key insight #2",
          "Key insight #3",
          "Share this thread! 🚀"
        ],
        linkedinPost: `Just processed: "${content.title || 'New Content'}"\n\nKey takeaways:\n\n→ Valuable insight #1\n→ Valuable insight #2\n→ Valuable insight #3\n\nWhat are your thoughts on this?\n\n#learning #growth`,
        newsletter: `# ${content.title || 'Weekly Insights'}\n\n## Summary\n\nThis content covers important topics worth exploring.\n\n## Key Takeaways\n\n1. **First Insight** - Explanation here\n2. **Second Insight** - Why this matters\n3. **Third Insight** - How to apply\n\n## Action Items\n\n- Review this content\n- Apply one key insight\n- Share with your network\n\n---\n*Thanks for reading!*`,
        tiktokClips: [
          {
            hook: "This one insight changed everything...",
            timestamp: { start: 30, end: 90 },
            script: "You won't believe this one thing that changed my entire approach..."
          },
          {
            hook: "Nobody talks about this...",
            timestamp: { start: 120, end: 180 },
            script: "The secret that most people miss..."
          }
        ],
        quoteGraphics: [
          `${content.title || 'Success'} is about showing up every day.`,
          "Consistency beats intensity.",
          "Your voice matters.",
          "Start before you're ready."
        ],
        seoSummary: `# ${content.title || 'Content Summary'}\n\nThis content explores important ideas and insights for content creators and professionals looking to improve their output and reach.\n\n## Key Topics\n\n- Content strategy and execution\n- Audience engagement techniques\n- Growth and optimization methods\n\n## Why This Matters\n\nUnderstanding these principles can help you create more impactful content and build stronger connections with your audience.`,
        instagramCaption: `Just shared something valuable 🔥\n\n"${content.title || 'New Content'}" is now available.\n\nKey highlights:\n→ Valuable insight #1\n→ Valuable insight #2\n→ Actionable advice\n\nSave this for later! 💾\n\n#content #growth #learning`,
        hashtags: [
          "contentcreator",
          "learning",
          "growth",
          "motivation",
          "inspiration",
          "tips",
          "advice",
          "success"
        ]
      };
    }

    // Delete existing outputs
    await prisma.output.deleteMany({
      where: { contentId: id },
    });

    // Create new outputs
    const outputPromises = [
      prisma.output.create({
        data: {
          contentId: id,
          format: 'twitter_thread',
          data: JSON.stringify(outputs.twitterThread),
        },
      }),
      prisma.output.create({
        data: {
          contentId: id,
          format: 'linkedin_post',
          data: JSON.stringify({ text: outputs.linkedinPost }),
        },
      }),
      prisma.output.create({
        data: {
          contentId: id,
          format: 'newsletter',
          data: JSON.stringify({ text: outputs.newsletter }),
        },
      }),
      prisma.output.create({
        data: {
          contentId: id,
          format: 'tiktok_clip',
          data: JSON.stringify(outputs.tiktokClips),
        },
      }),
      prisma.output.create({
        data: {
          contentId: id,
          format: 'quote_graphic',
          data: JSON.stringify(outputs.quoteGraphics),
        },
      }),
      prisma.output.create({
        data: {
          contentId: id,
          format: 'seo_summary',
          data: JSON.stringify({ text: outputs.seoSummary }),
        },
      }),
      prisma.output.create({
        data: {
          contentId: id,
          format: 'instagram_caption',
          data: JSON.stringify({
            caption: outputs.instagramCaption,
            hashtags: outputs.hashtags,
          }),
        },
      }),
    ];

    await Promise.all(outputPromises);

    // Update content status
    await prisma.content.update({
      where: { id },
      data: {
        status: 'completed',
        processedAt: new Date(),
        transcript,
      },
    });

    return NextResponse.json({ success: true, outputsGenerated: 7 });
  } catch (error) {
    console.error('Error generating outputs:', error);

    // Update status to failed
    await prisma.content.update({
      where: { id },
      data: { status: 'failed' },
    }).catch(() => {}); // Ignore if update fails

    return NextResponse.json(
      { error: 'Failed to generate outputs' },
      { status: 500 }
    );
  }
}
